// vue-tutorial/src/components/HoverCounter.vue
<template>
    <h2 @mouseover="increment">Hovered {{ count }} times</h2>
</template>

<script>
import CounterMixing from "../mixings/counter";

export default {
  name: "HoverCounter",
  data() {
      return {
          count: 100
      }
  },
  mixins: [CounterMixing]
  
};
</script>

<style scoped>
</style>

// react-redux-tutorial/src/Components/HOC/HoverCounter.js
import React, { Component } from 'react'
import withCounter from './withCounter';

class HoverCounter extends Component {

    render() {
        const { count, incrementCount } = this.props;
        return (
            <div>
                <h2 onMouseOver={incrementCount}>Hovered { count } times</h2>
            </div>
        )
    }
}

export default withCounter(HoverCounter)
