// react-redux-tutorial/src/Components/HOC/ClickCounter.js
import React, { Component } from 'react'
import withCounter from './withCounter';

class ClickCounter extends Component {

    render() {
        const { count, incrementCount } = this.props;
        return (
            <div>
                <button onClick={incrementCount} >Clicked { count } times</button>
            </div>
        )
    }
}

export default withCounter(ClickCounter)

// vue-tutorial/src/components/composition-api/ClickCounter.vue
<template>
  <div>
    <button @click="increment">Clicked {{ count }} times</button>
  </div>
</template>

<script>
import useCounter from "../../hooks/useCounter";
export default {
  name: "ClickCounter",
  setup() {
    const { count, increment } = useCounter(10, 5);
    return {
      count,
      increment,
    };
  },
};
</script>

<style scoped>
</style>
