// react-redux-tutorial/src/Components/HOC/HoverCounter.js
import React, { Component } from 'react'
import withCounter from './withCounter';

class HoverCounter extends Component {

    render() {
        const { count, incrementCount } = this.props;
        return (
            <div>
                <h2 onMouseOver={incrementCount}>Hovered { count } times</h2>
            </div>
        )
    }
}

export default withCounter(HoverCounter)

// vue-tutorial/src/components/composition-api/HoverCounter.vue
<template>
  <h2 @mouseover="increment">Hovered {{ count }} times</h2>
</template>

<script>
import useCounter from "../../hooks/useCounter";

export default {
  name: "HoverCounter",
  setup() {
    const { count, increment } = useCounter();
    return {
      count,
      increment,
    };
  },
};
</script>

<style scoped>
</style>
